version: '3.3'
services:
  backend:
    build:
      context: ./
    command: npm start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true